### PR TITLE
Updated doctrine-orm-module package dependency version

### PR DESCRIPTION
**Pull request by Kwido**
to ^1.0 instead of 0.*

### CODE REVIEW

**Comment by Kwido** [comment]
Master branch has been updated to include version 1.0+

**Comment by Kwido** [comment]
Master branch has been updated to include version 1.0+

**Comment by marden** [comment]
It'd be nice to have a tag version.

**Comment by Kwido** [comment]
@marden, yes it would be nice to see that.

@Danielss89, could you add a new tag for dependency upgrade of the docctrine-orm-module? Instead of using the master branch.

**Pull request closed without merging**
